name: hips

channels:
    - conda-forge

dependencies:
    - python=3.6
    - numpy
    - astropy
    - astropy-healpix
    - reproject
    - matplotlib
    - tqdm
    - aiohttp
    - sphinx
    - pip:
        - sphinx_rtd_theme
