name: hips

channels:
    - conda-forge
    - astropy

dependencies:
    # TODO: change to Python 3.6 once it's supported:
    # https://github.com/rtfd/readthedocs.org/issues/2584#issuecomment-304366679
    - python=3.5
    - numpy
    - astropy
    - healpy
    - reproject
    - matplotlib
    # There's a problem with Sphinx 1.6 with astropy-helpers
    # For now, we pin the Sphinx version to something that works
    - sphinx==1.5.6
    - pip:
        - sphinx_rtd_theme
